name: Deploy rust.leix.wang website
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        persist-credentials: false
    - name: Install and Build
      run: |
        npm install -g yarn
        yarn
        npm run-script build
        cd ./markdown/.vitepress/dist
        echo 'think.turingthink.site' > CNAME
        git init
        git config user.name "TuringThink"
        git config user.email "Richard@turingthink.site"
        git add -A
        git commit -m 'deploy'
        git push -f https://turingthink:${{ secrets.BUILD_THINK }}@github.com/turingthink/think.github.io.git master:gh-pages
        cd -